"""API module public surface."""

from __future__ import annotations

from .errors import (
    ApiConflictError,
    ApiError,
    ApiInternalError,
    ApiNotFoundError,
    ApiValidationError,
    map_workflow_error,
)
from .mappers import (
    map_approval_result,
    map_initiate_result,
    map_timeline_event,
    map_transition_record,
    map_workflow_history,
    map_workflow_output,
    map_workflow_status,
    map_workflow_timeline,
)
from .protocols import (
    ApiDependencies,
    ApiRouterFactory,
    MutatingRouteContext,
    ReadinessProbe,
    create_api_router,
)
from .routes import (
    METHOD_GET,
    METHOD_POST,
    PATH_HEALTH,
    PATH_READY,
    PATH_WORKFLOW_APPROVAL,
    PATH_WORKFLOW_BY_ID,
    PATH_WORKFLOW_HISTORY,
    PATH_WORKFLOW_OUTPUT,
    PATH_WORKFLOW_TIMELINE,
    PATH_WORKFLOWS,
    ROUTE_APPROVAL,
    ROUTE_HEALTH,
    ROUTE_HISTORY,
    ROUTE_INITIATE,
    ROUTE_MODULES,
    ROUTE_OUTPUT,
    ROUTE_READY,
    ROUTE_STATUS,
    ROUTE_TIMELINE,
)
from .routes.approval import handle_submit_approval
from .routes.health import handle_health, handle_readiness
from .routes.history import handle_get_workflow_history
from .routes.initiate import handle_initiate_workflow
from .routes.output import handle_get_workflow_output
from .routes.status import handle_get_workflow_status
from .routes.timeline import handle_get_workflow_timeline
from .types import (
    ApiErrorEnvelope,
    DependencyCheck,
    DependencyCheckStatus,
    HealthResponse,
    HealthStatus,
    InitiateWorkflowApiRequest,
    InitiateWorkflowApiResponse,
    ReadinessResponse,
    ReadinessStatus,
    SubmitApprovalApiRequest,
    SubmitApprovalApiResponse,
    TimelineEventResponse,
    TransitionRecordResponse,
    WorkflowHistoryResponse,
    WorkflowOutputResponse,
    WorkflowStatusResponse,
    WorkflowTimelineResponse,
)

__version__ = "0.1.0-draft"

__all__ = [
    "__version__",
    "ApiConflictError",
    "ApiDependencies",
    "ApiError",
    "ApiErrorEnvelope",
    "ApiInternalError",
    "ApiNotFoundError",
    "ApiRouterFactory",
    "ApiValidationError",
    "DependencyCheck",
    "DependencyCheckStatus",
    "HealthResponse",
    "HealthStatus",
    "InitiateWorkflowApiRequest",
    "InitiateWorkflowApiResponse",
    "MutatingRouteContext",
    "METHOD_GET",
    "METHOD_POST",
    "PATH_HEALTH",
    "PATH_READY",
    "PATH_WORKFLOW_APPROVAL",
    "PATH_WORKFLOW_BY_ID",
    "PATH_WORKFLOW_HISTORY",
    "PATH_WORKFLOW_OUTPUT",
    "PATH_WORKFLOW_TIMELINE",
    "PATH_WORKFLOWS",
    "ROUTE_APPROVAL",
    "ROUTE_HEALTH",
    "ROUTE_HISTORY",
    "ROUTE_INITIATE",
    "ROUTE_MODULES",
    "ROUTE_OUTPUT",
    "ROUTE_READY",
    "ROUTE_STATUS",
    "ROUTE_TIMELINE",
    "ReadinessProbe",
    "ReadinessResponse",
    "ReadinessStatus",
    "SubmitApprovalApiRequest",
    "SubmitApprovalApiResponse",
    "TimelineEventResponse",
    "TransitionRecordResponse",
    "WorkflowHistoryResponse",
    "WorkflowOutputResponse",
    "WorkflowStatusResponse",
    "WorkflowTimelineResponse",
    "create_api_router",
    "handle_get_workflow_history",
    "handle_get_workflow_output",
    "handle_get_workflow_status",
    "handle_get_workflow_timeline",
    "handle_health",
    "handle_initiate_workflow",
    "handle_readiness",
    "handle_submit_approval",
    "map_approval_result",
    "map_initiate_result",
    "map_timeline_event",
    "map_transition_record",
    "map_workflow_error",
    "map_workflow_history",
    "map_workflow_output",
    "map_workflow_status",
    "map_workflow_timeline",
]
